version: '3'
services:
  marina-backend:
    image: "puzzle/marina-backend"
    build:
      context: .
    environment:
      - SECURITY_OAUTH2_CLIENT_CLIENTID=clientid
      - SECURITY_OAUTH2_CLIENT_CLIENTSECRET=secret
      - SECURITY_OAUTH2_CLIENT_ACCESSTOKENURI=localhost
      - SECURITY_OAUTH2_CLIENT_USERAUTHORIZATIONURI=localhost
      - SECURITY_OAUTH2_RESOURCE_USERINFOURI=localhost
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/marina
      - SPRING_DATASOURCE_PASSWORD=marina
      - SPRING_DATASOURCE_USERNAME=marina
    ports:
     - "8080:8080"
    links:
     - postgresqldb

  postgresqldb:
    image: "centos/postgresql-96-centos7"
    environment:
      - POSTGRESQL_USER=marina
      - POSTGRESQL_PASSWORD=marina
      - POSTGRESQL_DATABASE=marina
    volumes:
      - 'posgresql-data:/var/lib/pgsql/data'

  postgresql-localdev:
    restart: unless-stopped
    ports:
      - "5432:5432"
    image: "centos/postgresql-96-centos7"
    environment:
      - POSTGRESQL_USER=marina
      - POSTGRESQL_PASSWORD=marina
      - POSTGRESQL_DATABASE=marina
    volumes:
      - 'posgresql-data:/var/lib/pgsql/data'

volumes:
  posgresql-data:
