version: '3'
services:

  marina-db:
    image: centos/postgresql-96-centos7
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      - POSTGRESQL_DATABASE=marina
      - POSTGRESQL_USER=marina
      - POSTGRESQL_PASSWORD=marina
    volumes:
      - marina-data:/var/lib/pgsql/data

  keycloak:
    image: jboss/keycloak:14.0.0
    restart: unless-stopped
    ports:
      - ${KEYCLOAK_PORT:-8090}:8080
    depends_on:
      - keycloak-db
    environment:
      - DB_ADDR=keycloak-db
      - DB_VENDOR=postgres
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/realm-export.json
    volumes:
      - ./devenv/keycloak/realm-export.json:/realm-export.json
      - ./devenv/keycloak/create-users.sh:/opt/jboss/startup-scripts/create-users.sh:ro

  keycloak-db:
    image: centos/postgresql-96-centos7
    restart: unless-stopped
    environment:
      - POSTGRESQL_DATABASE=keycloak
      - POSTGRESQL_USER=keycloak
      - POSTGRESQL_PASSWORD=password
    volumes:
      - keycloak-data:/var/lib/pgsql/data

volumes:
  marina-data:
  keycloak-data:
