# Use application.properties only for default values, use Environment Variables to configure the application

server:
  servlet:
    contextPath: /api


# Postgresql DB default Values
spring:
   database:
      driverClassName: org.postgresql.Driver
   datasource:
      url: jdbc:postgresql://localhost:5432/marina
      username: marina
      password: marina
# Oauth Client configuration
security:
  user:
    password: password
  oauth2:
    client:
      clientId:
      clientSecret:
      accessTokenUri:
      userAuthorizationUri:
      tokenName: access_token
      authenticationScheme: header
      clientAuthenticationScheme: header
    resource:
      userInfoUri:
  enable-csrf: false
  redirecturl: 
     frontend: /
